# verbose level 0=info, 1=verbose, 2=very verbose
verbose: 1
listen:
  # openssh
  - target_host: 127.0.0.1
    target_port: 22
    listen_port: 8080

  # dropbear  
  - target_host: 127.0.0.1
    target_port: 2222
    listen_port: 8081