#!/bin/bash

# Warna untuk output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Fungsi logging
print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

install_certificate() {
    clear
    print_info "INSTALLING CERTIFICATES..."

    # Buat folder cert
    mkdir -p /etc/certificates

    # Download dan install acme.sh
    curl https://get.acme.sh | sh

    # Masuk ke direktori acme.sh
    cd ~/.acme.sh

    # Set default CA ke Let's Encrypt & upgrade
    ./acme.sh --upgrade --auto-upgrade
    ./acme.sh --set-default-ca --server letsencrypt

    # Daftar akun
    ./acme.sh --register-account -m yuivpnstore@gmail.com

    # Issue cert baru pakai standalone mode dan ECC
    ./acme.sh --issue -d "$DOMAIN" --standalone -k ec-256 --force

    # Install cert ke /etc/certificates
    ./acme.sh --installcert -d "$DOMAIN" \
        --fullchainpath /etc/certificates/fullchain.crt \
        --keypath /etc/certificates/private.key \
        --ecc

    # Set permission (biar aman)
    chmod 600 /etc/certificates/*
    chown nobody:nogroup /etc/certificates/*
    
    # Delete File
    rm -rf .acme.sh >/dev/null 2>&1
    rm -rf -- "$0"

    print_ok "CERTIFICATES INSTALLED"
}