#!/bin/bash

# Warna untuk output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Fungsi logging
print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Konfigurasi Github
GITHUB_RAW="https://raw.githubusercontent.com"
GITHUB_USER="xenvoid404"
GITHUB_REPO="autoscript-tunneling"
GITHUB_REPO_BRANCH="master"
GITHUB_RAW_REPO="${GITHUB_RAW}/${GITHUB_USER}/${GITHUB_REPO}/${GITHUB_REPO_BRANCH}"

# Informasi domain
DOMAIN=`cat /etc/domain`
ADDR="s/xxxxxxxxx/$DOMAIN/g";

# Setup Directory
clear
print_info "INSTALLING OPENVPN..."
sleep 2

rm -rf /etc/openvpn
mkdir -p /etc/openvpn
curl -sS "${GITHUB_RAW_REPO}/openvpn/ovpn.zip" -o /etc/openvpn/ovpn.zip
unzip /etc/openvpn/ovpn.zip -d /etc/openvpn/ >/dev/null 2>&1
rm -rf /etc/openvpn/ovpn.zip

# Jalankan service openvpn
mkdir -p /user/lib/openvpn
cp /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so /usr/lib/openvpn/openvpn-plugin-auth-pam.so
sed -i 's/#AUTOSTART="all"/AUTOSTART="all"/g' /etc/default/openvpn
systemctl enable --now openvpn-server@server-tcp-1194
systemctl enable --now openvpn-server@server-udp-25000
/etc/init.d/openvpn restart

# Buat konfigurasi
echo 1 > /proc/sys/net/ipv4/ip_forward
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
cat > /etc/openvpn/myvpn-tcp-80.ovpn <<-END
auth-user-pass
client
dev tun
proto tcp
remote xxxxxxxxx 80
persist-key
persist-tun
pull
resolv-retry infinite
nobind
comp-lzo
remote-cert-tls server
verb 3
mute 2
connect-retry 5 5
connect-retry-max 8080
mute-replay-warnings
redirect-gateway def1
script-security 2
cipher none
auth none
END
sed -i $ADDR /etc/openvpn/myvpn-tcp-80.ovpn;
    
cat > /etc/openvpn/myvpn-udp-25000.ovpn <<-END
auth-user-pass
client
dev tun
proto udp
remote xxxxxxxxx 25000
persist-key
persist-tun
pull
resolv-retry infinite
nobind
comp-lzo
remote-cert-tls server
verb 3
mute 2
connect-retry 5 5
connect-retry-max 8080
mute-replay-warnings
redirect-gateway def1
script-security 2
cipher none
auth none
END
sed -i $ADDR /etc/openvpn/myvpn-udp-25000.ovpn;

cat > /etc/openvpn/myvpn-ssl-443.ovpn <<-END
auth-user-pass
client
dev tun
proto tcp
remote hcizktuxbo.svyp.cloud 443
persist-key
persist-tun
pull
resolv-retry infinite
nobind
comp-lzo
remote-cert-tls server
verb 3
mute 2
connect-retry 5 5
connect-retry-max 8080
mute-replay-warnings
redirect-gateway def1
script-security 2
cipher none
auth none
END
sed -i $ADDR /etc/openvpn/myvpn-ssl-443.ovpn;

# Install certificate
echo '<ca>' >> /etc/openvpn/myvpn-tcp-80.ovpn
cat /etc/openvpn/server/ca.crt >> /etc/openvpn/myvpn-tcp-80.ovpn
echo '</ca>' >> /etc/openvpn/myvpn-tcp-80.ovpn
echo '<ca>' >> /etc/openvpn/myvpn-udp-25000.ovpn
cat /etc/openvpn/server/ca.crt >> /etc/openvpn/myvpn-udp-25000.ovpn
echo '</ca>' >> /etc/openvpn/myvpn-udp-25000.ovpn
echo '<ca>' >> /etc/openvpn/myvpn-ssl-443.ovpn
cat /etc/openvpn/server/ca.crt >> /etc/openvpn/myvpn-ssl-443.ovpn
echo '</ca>' >> /etc/openvpn/myvpn-ssl-443.ovpn
cp /etc/openvpn/myvpn-tcp-80.ovpn /var/www/html/myvpn-tcp-80.ovpn
cp /etc/openvpn/myvpn-udp-25000.ovpn /var/www/html/myvpn-udp-25000.ovpn
cp /etc/openvpn/myvpn-ssl-443.ovpn /var/www/html/myvpn-ssl-443.ovpn

rm -rf -- "$0"

print_success "OPENVPN INSTALLED SUCCESSFULLY"